export declare function input_length(): u64;
export declare function input_load_u8(offs: u64): u8;
export declare function input_load_u64(offs: u64): u64;
export declare function length(a: u64): u64;
export declare function alloc(a: u64): u64;
export declare function free(a: u64): void;
export declare function output_set(a: u64, b: u64): void;
export declare function error_set(a: u64): void;
export declare function config_get(a: u64): u64;
export declare function var_get(a: u64): u64;
export declare function var_set(a: u64, b: u64): void;
export declare function store_u8(a: u64, b: u8): void;
export declare function load_u8(a: u64): u8;
export declare function store_u64(a: u64, b: u64): void;
export declare function load_u64(a: u64): u64;
export declare function http_request(a: u64, b: u64): u64;
export declare function log_warn(offs: u64): void;
export declare function log_info(offs: u64): void;
export declare function log_debug(offs: u64): void;
export declare function log_error(offs: u64): void;
